### ISSUE TITLE
Add authors information?

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/WorkshopPrace2021#34]
Aside from the welcome lecture there's no list of all the authors for the workshop.

I'd be good to add this somewhere, maybe an `AUTHOR.md` or directly in the `README`?

**Comment by orbeckst** [comment]
I'd add an AUTHORS file as usual.

The README could link to AUTHORS and also the blog post https://www.mdanalysis.org/2021/04/09/prace-workshop/
